{% set name = "fermitools-dependencies" %}
# {% set version = "1.0" %}

package:
  name: {{ name|lower }}
  version: {{ environ.get('VERSION', 0.0)}}

# source:
#   git_url: https://github.com/fermi-lat/Fermitools-dependencies.git
 
build:
  number: {{ environ.get('BUILD_NUMBER', 0)}}

requirements:
  host:
    - ape >=3
    - aplpy
    - astropy
    - blas
    - clhep 2.4.5
    - cppunit
    - f2c 0.0.2
    - fftw
    - fermitools-data
    - gsl
    - healpix_cxx
    - matplotlib
    - ncurses
    - numpy  >=1.17
    - openblas
    - pmw
    - python 3.7.*
    - pyyaml
    - readline
    - root 6.22.6
    - scipy
    - time
    - wcslib 5.*
    - xerces-c
    - zstd 
